service: cartoongrabber

plugins:
  - serverless-dynamodb-local
  - serverless-offline-scheduler
  - serverless-offline

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs12.x
  environment:
    CARTOON_TABLE: cartoons
    SLACK_TOKEN: ${ssm:/cartoongrabber-slack-secret~true}
    SLACK_CHANNEL_NAME: ${ssm:/cartoongrabber-slack-channel-name}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: '*'
  cfLogs: true

package:
  include:
    - handlers/**
    - handler.js
  exclude:
    - test/**

functions:
  grab:
    handler: handlers.grab
    events:
      - schedule: rate(4 hours)
  report:
    handler: handlers.report
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - CartoonsDynamoDbTable
              - StreamArn
          batchSize: 1

resources:
  Resources:
    CartoonsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      #      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: 'name'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'name'
            KeyType: 'HASH'
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: 'NEW_IMAGE'
        TableName: ${self:provider.environment.CARTOON_TABLE}
    GrabLogGroup:
      Properties:
        RetentionInDays: "14"
    ReportLogGroup:
      Properties:
        RetentionInDays: "14"

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: '8000'
      inMemory: true,
      migrate: true
