service: cartoongrabber

plugins:
  - serverless-offline

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs12.x

package:
  individually: true

functions:
  grab:
    handler: handlers/grabber.grab
    events:
      - http:
          method: get
          path: grab
