service: cartoongrabber

plugins:
  - serverless-dynamodb-local
  - serverless-offline-scheduler
  - serverless-offline

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs12.x
  environment:
    CARTOON_TABLE: cartoons
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"

package:
  individually: true

functions:
  grab:
    handler: handlers/grabber.grab
    events:
      - http:
          method: get
          path: grab
      - schedule: cron(* * * * * *)

resources:
  Resources:
    CartoonsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
#      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "name"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "name"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: ${self:provider.environment.CARTOON_TABLE}

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: "8000"
      inMemory: true,
      migrate: true
