service: cartoongrabber

plugins:
  - serverless-dynamodb-local
  - serverless-offline-scheduler
  - serverless-offline

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs12.x
  environment:
    CARTOON_TABLE: cartoons
    SLACK_TOKEN: ${ssm:/cartoongrabber-slack-secret~true}
    SLACK_CHANNEL_NAME: ${ssm:/cartoongrabber-slack-channel-name}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: '*'

package:
  include:
    - handlers/**
    - handler.js
  exclude:
    - test/**

functions:
  grab:
    handler: handlers.grab
    events:
      - http:
          method: get
          path: grab
      - schedule: rate(1 minute)
  report:
    handler: handlers.report
    events:
      - http:
          method: get
          path: report

resources:
  Resources:
    CartoonsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      #      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: 'name'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'name'
            KeyType: 'HASH'
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: 'NEW_AND_OLD_IMAGES'
        TableName: ${self:provider.environment.CARTOON_TABLE}

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: '8000'
      inMemory: true,
      migrate: true
